// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(ResidentProDbContext))]
    [Migration("20251119104217_UpdateReportSchema")]
    partial class UpdateReportSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("server.Models.EventHall", b =>
                {
                    b.Property<int>("HBookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hBookingID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HBookingID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("bookingDate");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("startTime");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<int>("VenueID")
                        .HasColumnType("int")
                        .HasColumnName("venueID");

                    b.HasKey("HBookingID");

                    b.HasIndex("UserID");

                    b.HasIndex("VenueID");

                    b.ToTable("event_hall", (string)null);
                });

            modelBuilder.Entity("server.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("facilityID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("hourlyRate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("facility", (string)null);
                });

            modelBuilder.Entity("server.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoiceID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("invoiceDate");

                    b.Property<TimeSpan>("InvoiceTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("invoiceTime");

                    b.Property<int>("PaymentID")
                        .HasColumnType("int")
                        .HasColumnName("paymentID");

                    b.HasKey("InvoiceID");

                    b.HasIndex("PaymentID");

                    b.ToTable("invoice", (string)null);
                });

            modelBuilder.Entity("server.Models.Login", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Email");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("login", (string)null);
                });

            modelBuilder.Entity("server.Models.ManagementFee", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dueDate");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issueDate");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("method");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("paymentDate");

                    b.Property<TimeSpan>("PaymentTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("paymentTime");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int")
                        .HasColumnName("propertyID");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("PaymentID");

                    b.HasIndex("PropertyID");

                    b.ToTable("management_fee", (string)null);
                });

            modelBuilder.Entity("server.Models.Property", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("propertyID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PropertyID"));

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("block");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("floor");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.HasKey("PropertyID");

                    b.ToTable("property", (string)null);
                });

            modelBuilder.Entity("server.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reportID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<string>("AssignedTo")
                        .HasColumnType("longtext")
                        .HasColumnName("assignedTo");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("PhotoBase64")
                        .HasColumnType("longtext")
                        .HasColumnName("photoBase64");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("priority");

                    b.Property<int>("ReportStatus")
                        .HasColumnType("int")
                        .HasColumnName("reportStatus");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("longtext")
                        .HasColumnName("resolutionNotes");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resolvedDate");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("subject");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submittedDate");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("ReportID");

                    b.HasIndex("UserID");

                    b.ToTable("report", (string)null);
                });

            modelBuilder.Entity("server.Models.SportFacility", b =>
                {
                    b.Property<int>("SBookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sBookingID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SBookingID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("bookingDate");

                    b.Property<int>("Court")
                        .HasColumnType("int")
                        .HasColumnName("court");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sportName");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("startTime");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("SBookingID");

                    b.HasIndex("UserID");

                    b.ToTable("sport_facility", (string)null);
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("PropertyID");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("server.Models.Venue", b =>
                {
                    b.Property<int>("VenueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("venueID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VenueID"));

                    b.Property<string>("VenueDescription")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("venueDescription");

                    b.Property<byte[]>("VenueImg")
                        .HasColumnType("longblob")
                        .HasColumnName("venueImg");

                    b.HasKey("VenueID");

                    b.ToTable("venue", (string)null);
                });

            modelBuilder.Entity("server.Models.Visitor", b =>
                {
                    b.Property<int>("VisitorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("visitorID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VisitorID"));

                    b.Property<string>("CarPlate")
                        .HasColumnType("longtext")
                        .HasColumnName("carPlate");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("checkOutTime");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("purpose");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("visitDate");

                    b.Property<TimeSpan>("VisitTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("visitTime");

                    b.Property<string>("VisitorContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("visitorContactNumber");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("visitorName");

                    b.HasKey("VisitorID");

                    b.HasIndex("UserID");

                    b.ToTable("visitor", (string)null);
                });

            modelBuilder.Entity("server.Models.EventHall", b =>
                {
                    b.HasOne("server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("server.Models.Invoice", b =>
                {
                    b.HasOne("server.Models.ManagementFee", "ManagementFee")
                        .WithMany()
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagementFee");
                });

            modelBuilder.Entity("server.Models.Login", b =>
                {
                    b.HasOne("server.Models.User", "User")
                        .WithOne("Login")
                        .HasForeignKey("server.Models.Login", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.ManagementFee", b =>
                {
                    b.HasOne("server.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("server.Models.Report", b =>
                {
                    b.HasOne("server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.SportFacility", b =>
                {
                    b.HasOne("server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.HasOne("server.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("server.Models.Visitor", b =>
                {
                    b.HasOne("server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Navigation("Login");
                });
#pragma warning restore 612, 618
        }
    }
}
